### ISSUE TITLE
Problem with Python

### ISSUE THREAD

**Issue by arthurlg** [jaj42/GraPhysio#1]
Hi

I've downloaded Anaconda, Python 3.5, PyQt and clone this GIT.
I've tried to launch the DynGraph.pwy but an ImportError comes: No module named 'dyngraph.mainui'

My version of PyQt is 5.

Have you an idea?

**Comment by jaj42** [comment]
You need to install the dyngraph package. Try to type 'python setup.py install' in the DynGraph folder. Also I don't know if PyQt 5 will work, I only tested with PyQt 4.

**Comment by arthurlg** [comment]
Ok, 

I can launch the package now. But it seems to have issues with path. For example:
  File "C:\Users\Geronimo\Anaconda3\lib\site-packages\dyngraph-0.2-py3.5.egg\dyngraph\exporter.py", line 8, in <module>
    from dyngraph.ui import Ui_PeriodExport

**Comment by jaj42** [comment]
Bizarre, je ne sais pas trop pourquoi. La fenetre du programme s'ouvre ou pas? Tu pourrais essayer en faisant "python setup.py develop"? Sinon on peut regarder ca ensemble. P.ex. le 9 je serai a Saclay.

**Comment by arthurlg** [comment]
Hello,

J'ai essayé d'installer dyngraph sur mon mac.
En 1 j'ai installé anaconda. J'ai cloné le dossier dyngraph depuis github.
Et âpres quand je lance le dyngraph.py, j'ai l'erreur suivante :
"jellyfish:~ arthur$ cd '/Volumes/Data/arthur/dyngraph/scripts/' && '/usr/bin/pythonw'  '/Volumes/Data/arthur/dyngraph/scripts/DynGraph.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Volumes/Data/arthur/dyngraph/scripts/DynGraph.py", line 2, in <module>
    from PyQt4 import QtGui
ImportError: No module named PyQt4
jellyfish:scripts arthur$ "

J'ai probablement manqué quelque chose dans l'installation.

Bises et merci pour le debugging

**Comment by jaj42** [comment]
Il semble que tu n'aies pas PyQt4. Normalement tu peux l'installer en tapant dans la ligne de commande:
conda install pyqt=4

**Comment by arthurlg** [comment]
ellyfish:~ arthur$ conda install pyqt=4
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Volumes/Data/arthur/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    requests-2.12.4            |           py35_0         792 KB
    qt-4.8.7                   |                4        37.1 MB
    pyqt-4.11.4                |           py35_4         4.0 MB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.4                |           py35_0         487 KB
    ------------------------------------------------------------
                                           Total:        42.4 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0      

The following packages will be UPDATED:

    conda:     4.2.9-py35_0  --> 4.3.4-py35_0 
    pyopenssl: 16.0.0-py35_0 --> 16.2.0-py35_0
    requests:  2.11.1-py35_0 --> 2.12.4-py35_0

The following packages will be DOWNGRADED due to dependency conflicts:

    pyqt:      5.6.0-py35_0  --> 4.11.4-py35_4
    qt:        5.6.0-0       --> 4.8.7-4      

Proceed ([y]/n)? 

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 419.15 kB/s
requests-2.12. 100% |################################| Time: 0:00:00   9.85 MB/s
qt-4.8.7-4.tar 100% |################################| Time: 0:00:02  14.46 MB/s
pyqt-4.11.4-py 100% |################################| Time: 0:00:00   5.74 MB/s
pyopenssl-16.2 100% |################################| Time: 0:00:00   9.27 MB/s
conda-4.3.4-py 100% |################################| Time: 0:00:00  13.86 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
jellyfish:~ arthur$ /Volumes/Data/arthur/dyngraph/scripts/DynGraph.py 
-bash: /Volumes/Data/arthur/dyngraph/scripts/DynGraph.py: Permission denied
jellyfish:~ arthur$ /Volumes/Data/arthur/dyngraph/scripts/DynGraph.py
-bash: /Volumes/Data/arthur/dyngraph/scripts/DynGraph.py: Permission denied
jellyfish:~ arthur$ /Volumes/Data/arthur/dyngraph/setup.py 
-bash: /Volumes/Data/arthur/dyngraph/setup.py: Permission denied
jellyfish:~ arthur$
